import logging
from contextlib import contextmanager
from pathlib import Path
from uuid import uuid4
from app.core.config import get_settings
from app.core.exceptions import AppError

logger = logging.getLogger(__name__)


def storage_path(key: str) -> Path:
    root = get_settings().storage_dir.resolve()
    path = (root / key).resolve()
    if path.parent != root or not key or Path(key).name != key:
        raise AppError(500, "Invalid stored document location.")
    return path


def save_file(key: str, content: bytes) -> Path:
    path = storage_path(key)
    created = False
    try:
        path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        with path.open("xb") as target:
            created = True
            path.chmod(0o600)
            target.write(content)
    except OSError:
        # The key is generated by this request, never supplied by a user.
        if created:
            path.unlink(missing_ok=True)
        raise AppError(503, "Document storage is unavailable. Please retry.") from None
    return path


@contextmanager
def staged_deletion(keys: list[str]):
    """Keep bytes recoverable until the database transaction commits."""
    moved = []
    try:
        for key in keys:
            original = storage_path(key)
            if original.exists():
                staged = original.with_name(f".trash-{uuid4().hex}")
                original.rename(staged)
                moved.append((original, staged))
        yield
    except Exception:
        for original, staged in reversed(moved):
            staged.rename(original)
        raise
    else:
        for _, staged in moved:
            try:
                staged.unlink(missing_ok=True)
            except OSError:
                logger.warning("Deferred document trash cleanup required")
