/* eslint-disable @typescript-eslint/no-require-imports -- CommonJS harness installs a TypeScript loader for isolated service tests. */
// V5 business rules: lifecycle, appeals, moderation, audit, feedback, quotas, auth hardening, migration.
const assert = require('node:assert/strict');
const { store } = require('./test-harness.cjs');
const load = name => require(`../src/${name}.ts`);
const { authService } = load('services/auth.service');
const { chatbotService } = load('services/chatbot.service');
const { knowledgeService } = load('services/knowledge.service');
const { channelService } = load('services/channel.service');
const { publicChatService } = load('services/public-chat.service');
const { adminService } = load('services/admin.service');
const { appealService } = load('services/appeal.service');
const { auditService } = load('services/audit.service');
const { feedbackService } = load('services/feedback.service');
const { moderationService } = load('services/moderation.service');
const { insightsService } = load('services/insights.service');
const { platformService } = load('services/platform.service');
const { notificationService } = load('services/notification.service');
const { quotaService } = load('services/quota.service');
const { catalogService } = load('services/catalog.service');
const { knowledgeRepository } = load('repositories/knowledge.repository');
const { userRepository } = load('repositories/auth.repository');
const { demoConfig } = load('config/demo-config');
const { verificationRepository } = load('repositories/v5.repository');
const { purgeExpiredAccounts } = load('services/account-data');
const { totp } = load('utils/totp');
const { detectLanguage } = load('utils/language');
const { KEYS } = load('storage/keys');
const pdf = (name, size = 18000) => ({ name, size, type: 'application/pdf' });
const ready = async (bot, doc) => { knowledgeRepository.put({ ...doc, processingStartedAt: new Date(Date.now() - 6000).toISOString() }); return knowledgeService.list(bot); };
const asUser = (email, pass = '123') => authService.login(email, pass);
const asAdmin = () => asUser('admin@gmail.com');
(async () => {
  // --- v2 -> v5 migration: runs on the very first service call, before anything is seeded ---
  const legacy = (name, value) => { store[`ragcraft:v2:${name}`] = JSON.stringify(value); window.localStorage.setItem(`ragcraft:v2:${name}`, JSON.stringify(value)); };
  const d = new Date().toISOString();
  legacy('users', [{ id: 'old_user', email: 'old@example.com', full_name: 'Old', password: 'oldpass12', role: 'USER', builtIn: false, is_active: false, organization_id: 'old_user', organization_name: 'x', created_at: d, updated_at: d }]);
  legacy('chatbots', [{ id: 'old_bot', ownerId: 'old_user', organization_id: 'old_user', name: 'Old Bot', description: '', status: 'INACTIVE', created_at: d, updated_at: d, document_count: 0, ready_count: 0, failed_count: 0, settings: { model_name: 'Llama 3.2 3B', system_instruction: 'x', temperature: 0.2, top_k: 5, answer_length: 'LONG', tone: 'EDUCATIONAL' } }]);
  legacy('seeded', true);
  await asUser('admin@gmail.com');
  const migrated = await adminService.users();
  const old = migrated.find(u => u.email === 'old@example.com');
  assert.equal(old.status, 'SUSPENDED', 'inactive v2 user becomes SUSPENDED');
  const oldBot = (await adminService.bots()).find(b => b.id === 'old_bot');
  assert.equal(oldBot.status, 'PAUSED', 'INACTIVE bot becomes PAUSED');
  assert.ok(window.localStorage.getItem('ragcraft:v2:users'), 'v2 data is left untouched');
  await authService.logout();

  // --- password policy, generic errors, lock-out with growing duration ---
  await assert.rejects(authService.register({ full_name: 'A', email: 'a@example.com', password: 'short', confirm_password: 'short', terms: true }), /8–64/);
  await assert.rejects(authService.register({ full_name: 'A', email: 'a@example.com', password: 'password123', confirm_password: 'password123', terms: true }), /common/);
  await assert.rejects(authService.register({ full_name: 'A', email: 'a@example.com', password: 'a@example.com', confirm_password: 'a@example.com', terms: true }), /same as your email/);
  await assert.rejects(authService.register({ full_name: 'A', email: 'a@example.com', password: 'long-enough-1', confirm_password: 'long-enough-1', terms: false }), /Terms/);
  await authService.register({ full_name: 'Owner', email: 'owner@example.com', password: 'owner-pass-1', confirm_password: 'owner-pass-1', terms: true });
  await assert.rejects(authService.login('nobody@example.com', 'whatever1'), /Invalid email or password/);
  for (let i = 0; i < 4; i++) await assert.rejects(authService.login('owner@example.com', 'wrong-pass-1'), /Invalid email or password/);
  await assert.rejects(authService.login('owner@example.com', 'wrong-pass-1'), /Try again in 1 minute\./);
  await assert.rejects(authService.login('owner@example.com', 'owner-pass-1'), /Try again/, 'a locked account rejects even the right password');
  const lockRow = () => userRepository.all().find(u => u.email === 'owner@example.com');
  userRepository.put({ ...lockRow(), locked_until: new Date(Date.now() - 1000).toISOString() });
  for (let i = 0; i < 4; i++) await assert.rejects(authService.login('owner@example.com', 'wrong-pass-1'), /Invalid/);
  await assert.rejects(authService.login('owner@example.com', 'wrong-pass-1'), /Try again in 2 minutes\./);
  userRepository.put({ ...lockRow(), locked_until: null });
  await asUser('owner@example.com', 'owner-pass-1');
  assert.equal(lockRow().lock_count, 0, 'a successful sign-in resets the lock counter');

  // --- email verification (simulated) ---
  demoConfig.autoVerifyEmail = false;
  const unverified = await authService.register({ full_name: 'Late', email: 'late@example.com', password: 'late-pass-12', confirm_password: 'late-pass-12', terms: true });
  assert.equal(unverified.status, 'UNVERIFIED');
  await assert.rejects(authService.login('late@example.com', 'late-pass-12'), /Verify your email/);
  const resend = await authService.resendVerification('late@example.com');
  assert.match(resend.message, /If an unverified account exists/);
  verificationRepository.put({ id: 'expired_token', userId: unverified.id, kind: 'EMAIL', email: 'late@example.com', expires: Date.now() - 1000 });
  await assert.rejects(authService.verifyEmail('expired_token'), /expired/);
  await authService.verifyEmail(resend.token);
  await asUser('late@example.com', 'late-pass-12');
  demoConfig.autoVerifyEmail = true;
  await authService.logout();
  assert.equal((await authService.forgot('ghost@example.com')).message, (await authService.forgot('owner@example.com')).message, 'forgot-password never reveals whether an account exists');

  // --- chatbot creation rules ---
  await asUser('owner@example.com', 'owner-pass-1');
  await assert.rejects(chatbotService.create({ name: 'x'.repeat(51), description: '' }), /50 characters/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: 'd'.repeat(201) }), /200 characters/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: '', starter_questions: ['1', '2', '3', '4', '5'] }), /up to 4/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: '', settings: { tone: 'SHOUTY' } }), /Tone/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: '', settings: { tone: 'CUSTOM' } }), /custom tone/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: '', settings: { model_name: 'Not Allowed' } }), /primary model/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: '', settings: { embedding_model: 'nope' } }), /embedding model/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: '', settings: { temperature: 1.5 } }), /Temperature must be between 0 and 1/);
  await assert.rejects(chatbotService.create({ name: 'Bot', description: '', settings: { fallback_model_name: 'Llama 3.2 3B' } }), /must differ/);
  const bot = await chatbotService.create({ name: 'Lifecycle Bot', description: 'x', status: 'ACTIVE', settings: { fallback_model_name: 'Qwen', embedding_model: 'bge-m3' } });
  assert.equal(bot.status, 'DRAFT', 'new chatbots always start as DRAFT, whatever status is requested');
  assert.equal(bot.settings.temperature, 0.4); assert.equal(bot.settings.chunk_size, 500); assert.equal(bot.settings.search_mode, 'HYBRID'); assert.equal(bot.settings.answer_from_documents_only, true);
  await assert.rejects(chatbotService.update(bot.id, { name: bot.name, description: '', settings: { embedding_model: 'nomic-embed-text' } }), /cannot be changed/);
  await assert.rejects(chatbotService.update(bot.id, { name: bot.name, description: '', status: 'ACTIVE' }), /Add at least one document/);
  assert.equal((await chatbotService.checklist(bot.id)).ready, false);

  // --- knowledge: validation, duplicates, quota, filters, status sync ---
  await assert.rejects(knowledgeService.upload(bot.id, { name: 'notes.exe', size: 10 }), /not supported/);
  await assert.rejects(knowledgeService.upload(bot.id, pdf('huge.pdf', 21 * 1024 * 1024)), /exceeds the 20 MB/);
  const doc = await knowledgeService.upload(bot.id, pdf('Policy.pdf'));
  await assert.rejects(knowledgeService.upload(bot.id, pdf('policy.PDF')), /already exists/);
  assert.equal((await knowledgeService.upload(bot.id, pdf('policy.pdf'), 'SKIP')).id, doc.id);
  const replaced = await knowledgeService.upload(bot.id, pdf('policy.pdf', 9000), 'REPLACE');
  assert.equal(replaced.id, doc.id); assert.equal((await knowledgeService.list(bot.id)).length, 1);
  assert.equal((await chatbotService.get(bot.id)).status, 'DRAFT', 'still DRAFT while indexing');
  await ready(bot.id, replaced);
  assert.equal((await chatbotService.get(bot.id)).status, 'PENDING', 'a READY document moves DRAFT to PENDING');
  await assert.rejects(knowledgeService.retry(bot.id, doc.id), /Only failed/);
  await knowledgeService.rename(bot.id, doc.id, 'Handbook.pdf');
  assert.equal((await knowledgeService.list(bot.id, { search: 'hand' })).length, 1);
  assert.equal((await knowledgeService.list(bot.id, { status: 'FAILED' })).length, 0);
  const broken = await knowledgeService.upload(bot.id, pdf('corrupt-scan.pdf'));
  knowledgeRepository.put({ ...broken, processingStartedAt: new Date(Date.now() - 6000).toISOString() });
  const failed = (await knowledgeService.list(bot.id, { status: 'FAILED' }))[0];
  assert.match(failed.error_message, /could not be read/);
  assert.ok((await notificationService.list('PUSH')).some(n => n.type === 'KB_PROCESSING_FAILED'), 'failure notifies the owner');
  await knowledgeService.delete(bot.id, broken.id);
  await assert.rejects(knowledgeService.crawlPreview(bot.id, { start_url: 'https://example.com', max_depth: 4, max_pages: 60 }), /depth/);
  await assert.rejects(knowledgeService.crawlPreview(bot.id, { start_url: 'https://example.com', max_depth: 2, max_pages: 10 }), /50 to 100/);
  const crawl = await knowledgeService.crawlPreview(bot.id, { start_url: 'https://example.com', max_depth: 3, max_pages: 60 });
  assert.ok(crawl.length > 1 && crawl.some(p => p.status === 'BLOCKED'));
  const imported = await knowledgeService.importCrawl(bot.id, crawl);
  assert.equal(imported.length, crawl.filter(p => p.status === 'OK').length);

  // --- publish checklist, pause/resume, guest messages ---
  await assert.rejects(chatbotService.publish(bot.id), /one channel/);
  const link = await channelService.create(bot.id, 'PUBLIC_LINK');
  assert.equal((await chatbotService.checklist(bot.id)).ready, true);
  await chatbotService.publish(bot.id);
  assert.equal((await chatbotService.get(bot.id)).status, 'ACTIVE');
  await assert.rejects(chatbotService.update(bot.id, { name: bot.name, description: '', status: 'DRAFT' }), /cannot move/);
  await chatbotService.pause(bot.id);
  await assert.rejects(publicChatService.metadata('share', link.public_id), /temporarily unavailable/);
  await chatbotService.resume(bot.id);
  assert.equal((await publicChatService.metadata('share', link.public_id)).name, 'Lifecycle Bot');
  const widget = await channelService.create(bot.id, 'WEB_WIDGET');
  await channelService.save(bot.id, widget.id, { ...widget.settings, domains: ['HTTPS://Example.com/path', 'example.com', 'shop.example.com'] });
  assert.deepEqual((await channelService.list(bot.id)).find(c => c.id === widget.id).settings.domains, ['example.com', 'shop.example.com']);
  const telegram = await channelService.create(bot.id, 'TELEGRAM', 'not-a-token');
  assert.equal(telegram.status, 'ERROR'); assert.match(telegram.error_reason, /token is not valid/);
  const connected = await channelService.connect(bot.id, telegram.id, '123456789:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
  assert.equal(connected.status, 'LIVE'); assert.equal(connected.token_mask, 'Demo token ••••');
  assert.equal((await channelService.disconnect(bot.id, telegram.id)).status, 'OFF');
  await channelService.toggle(bot.id, await channelService.regenerate(bot.id, widget.id));
  const widgetOn = (await channelService.list(bot.id)).find(c => c.id === widget.id);
  assert.ok(widgetOn.enabled);
  await assert.rejects(publicChatService.metadata('widget', widgetOn.public_id, undefined, 'evil.com'), /not allowed/);
  assert.ok(await publicChatService.metadata('widget', widgetOn.public_id, undefined, 'blog.shop.example.com'));

  // --- answers, language, unanswered tracking, feedback and reports ---
  assert.equal(detectLanguage('សួស្តី អ្នកទាំងអស់គ្នា hello'), 'KM'); assert.equal(detectLanguage('안녕하세요 hi'), 'KO'); assert.equal(detectLanguage('hello'), 'EN');
  const known = await publicChatService.ask('share', link.public_id, 'What is the refund policy?', undefined, 'guest-1');
  assert.ok(known.sources.length >= 1);
  const unknown = await publicChatService.ask('share', link.public_id, 'Tell me about the moon', known.conversation_id, 'guest-1');
  assert.match(unknown.answer, /Sorry, I couldn't find that in my knowledge base\./); assert.equal(unknown.sources.length, 0);
  const korean = await publicChatService.ask('share', link.public_id, '달에 대해 알려주세요', undefined, 'guest-2');
  assert.match(korean.answer, /죄송합니다/);
  await feedbackService.rate('share', link.public_id, known.message_id, 'HELPFUL');
  await assert.rejects(feedbackService.report('share', link.public_id, known.message_id, 'INACCURATE'), /already sent feedback/);
  await assert.rejects(feedbackService.report('share', link.public_id, unknown.message_id, 'RUDE'), /reason/);
  await feedbackService.report('share', link.public_id, unknown.message_id, 'INACCURATE', 'The moon is in the docs');
  await assert.rejects(feedbackService.rate('share', link.public_id, 'forged_id', 'HELPFUL'), /no longer available/);
  const reports = await feedbackService.reports(bot.id, { status: 'OPEN', reason: 'INACCURATE' });
  assert.equal(reports.length, 1); assert.equal(reports[0].question, 'Tell me about the moon'); assert.equal(reports[0].channel, 'PUBLIC_LINK');
  assert.ok((await notificationService.list('PUSH')).some(n => n.type === 'REPORT_INACCURATE'));
  await feedbackService.setStatus(bot.id, reports[0].id, 'RESOLVED');
  await assert.rejects(feedbackService.setStatus(bot.id, reports[0].id, 'DISMISSED'), /already been handled/);
  const quality = await insightsService.answerQuality(bot.id);
  assert.equal(quality.helpful, 1); assert.equal(quality.reports_total, 1); assert.equal(quality.reports_open, 0);
  assert.ok(quality.unanswered.some(q => q.question === 'tell me about the moon')); assert.ok(quality.most_asked.length >= 2);
  const overview = await insightsService.botOverview(bot.id);
  assert.equal(overview.guests, 2); assert.equal(overview.sessions, 2); assert.ok(overview.active_sessions >= 2); assert.equal(overview.trends.DAILY.length, 14); assert.equal(overview.trends.WEEKLY.length, 8); assert.equal(overview.trends.MONTHLY.length, 6);
  assert.ok((await insightsService.channelBreakdown(bot.id)).find(c => c.channel === 'PUBLIC_LINK').messages >= 6);
  const listed = await chatbotService.list({ search: 'lifecycle', status: 'ACTIVE', sort: 'MESSAGES' });
  assert.equal(listed.length, 1); assert.equal(listed[0].kb_status, 'PROCESSING', 'imported crawl pages are still indexing'); assert.ok(listed[0].channel_count >= 3);

  // --- quota ---
  assert.deepEqual((await quotaService.usage()).bots, { used: 1, limit: 5 });
  await authService.logout(); await asAdmin();
  const owner = (await adminService.users('owner@')).find(u => u.email === 'owner@example.com');
  await assert.rejects(adminService.setQuota(owner.id, { max_bots: 6, max_storage_bytes: 100 }, 'too many'), /1 to 5/);
  await assert.rejects(adminService.setQuota(owner.id, { max_bots: 1, max_storage_bytes: 100 }, ' '), /reason/);
  await adminService.setQuota(owner.id, { max_bots: 1, max_storage_bytes: 5 * 1024 ** 3 }, 'trial plan');
  await authService.logout(); await asUser('owner@example.com', 'owner-pass-1');
  await assert.rejects(chatbotService.create({ name: 'Second', description: '' }), /Chatbot limit reached/);
  await authService.logout(); await asAdmin();
  await adminService.setQuota(owner.id, { max_bots: 5, max_storage_bytes: 20000 }, 'storage test');
  await authService.logout(); await asUser('owner@example.com', 'owner-pass-1');
  await assert.rejects(knowledgeService.upload(bot.id, pdf('big.pdf', 19000)), /Storage limit reached/);
  await authService.logout(); await asAdmin();
  await adminService.setQuota(owner.id, { max_bots: 5, max_storage_bytes: 5 * 1024 ** 3 }, 'restore');
  assert.ok((await adminService.users('', 0, { over_quota: true })).every(u => u.over_quota));

  // --- admin: platform limits, disable, appeals, moderation, audit ---
  await assert.rejects(platformService.setLimit('temperature', { min: 0, max: 2, default: 0.4 }), /within 0–1/);
  await platformService.setLimit('top_k', { min: 1, max: 10, default: 3 });
  await authService.logout(); await asUser('owner@example.com', 'owner-pass-1');
  await assert.rejects(chatbotService.update(bot.id, { name: bot.name, description: '', settings: { top_k: 15 } }), /Top K results must be between 1 and 10/);
  await authService.logout(); await asAdmin();
  const reportedBots = await moderationService.reportedBots();
  assert.equal(reportedBots.length, 1); assert.equal(reportedBots[0].open_reports, 0); assert.equal(reportedBots[0].total_reports, 1);
  const review = await moderationService.review(bot.id);
  assert.equal(review.reports.length, 1); assert.ok(review.documents.length >= 1);
  await assert.rejects(adminService.disableBot(bot.id, '  '), /reason/);
  await adminService.disableBot(bot.id, 'Spam content');
  await assert.rejects(adminService.disableBot(bot.id, 'again'), /already disabled/);
  await authService.logout(); await asUser('owner@example.com', 'owner-pass-1');
  assert.equal((await chatbotService.get(bot.id)).disabled_reason, 'Spam content');
  await assert.rejects(chatbotService.resume(bot.id), /disabled by an administrator/);
  await assert.rejects(publicChatService.metadata('share', link.public_id), /has been disabled/);
  await assert.rejects(appealService.submit(bot.id, ''), /Describe why/);
  await assert.rejects(appealService.submit(bot.id, 'x'.repeat(501)), /500 characters/);
  const appeal = await appealService.submit(bot.id, 'It was a mistake.');
  await assert.rejects(appealService.submit(bot.id, 'again'), /pending appeal/);
  assert.ok((await notificationService.list('EMAIL')).some(n => n.type === 'CHATBOT_DISABLED'));
  await authService.logout(); await asAdmin();
  assert.equal(await appealService.pendingCount(), 1);
  await assert.rejects(appealService.reject(appeal.id, ''), /reason is required/);
  await appealService.reject(appeal.id, 'Still violates policy');
  await assert.rejects(appealService.approve(appeal.id), /already been decided/);
  await authService.logout(); await asUser('owner@example.com', 'owner-pass-1');
  const second = await appealService.submit(bot.id, 'Content removed.');
  assert.equal((await appealService.forBot(bot.id)).find(a => a.status === 'REJECTED').decision_reason, 'Still violates policy');
  await authService.logout(); await asAdmin();
  await appealService.approve(second.id, 'Looks fine now');
  assert.equal((await chatbotService.get(bot.id)).status, 'PAUSED', 'an approved appeal returns the chatbot as PAUSED');
  await adminService.disableBot(bot.id, 'Second strike');
  await adminService.reenableBot(bot.id, 'Reviewed offline');
  assert.equal((await chatbotService.get(bot.id)).status, 'PAUSED');
  const log = await auditService.list();
  assert.deepEqual([...new Set(log.map(e => e.action))].sort(), ['APPROVE_APPEAL', 'FORCE_DISABLE_CHATBOT', 'REENABLE_CHATBOT', 'REJECT_APPEAL', 'SET_QUOTA'].sort());
  assert.equal((await auditService.list({ action: 'REJECT_APPEAL' })).length, 1);
  assert.equal((await auditService.get(log[0].id)).reason.length > 0, true);
  assert.equal((await auditService.list({ from: '2999-01-01' })).length, 0);

  // --- suspension, forced logout, sessions, MFA ---
  await authService.logout(); await asUser('owner@example.com', 'owner-pass-1');
  await asUser('owner@example.com', 'owner-pass-1');
  assert.equal((await authService.sessions()).length >= 2, true);
  await authService.revokeOtherSessions();
  assert.equal((await authService.sessions()).length, 1); assert.equal((await authService.sessions())[0].current, true);
  const setup = await authService.beginTotpSetup();
  await assert.rejects(authService.enableTotp(setup.secret, '000000'), /not valid/);
  await authService.enableTotp(setup.secret, await totp(setup.secret));
  assert.equal((await authService.me()).totp_enabled, true);
  await authService.logout();
  await assert.rejects(authService.login('owner@example.com', 'owner-pass-1'), /6-digit code/);
  await assert.rejects(authService.login('owner@example.com', 'owner-pass-1', { otp: '000000' }), /not valid/);
  await authService.login('owner@example.com', 'owner-pass-1', { otp: await totp(setup.secret), remember: true });
  await authService.addPasskey('Laptop');
  await authService.logout();
  assert.equal((await authService.loginWithPasskey('owner@example.com')).passkey_count, 1);
  // A session revoked by an admin stops working even though this browser still holds it.
  await authService.login('owner@example.com', 'owner-pass-1', { otp: await totp(setup.secret) });
  const ownerSession = window.localStorage.getItem(KEYS.session);
  await authService.logout(); await asAdmin();
  await adminService.forceLogout(owner.id, 'security check');
  window.localStorage.setItem(KEYS.session, ownerSession);
  await assert.rejects(authService.me(), /signed out/);
  await asAdmin();
  await adminService.resetMfa(owner.id, 'lost phone');
  await adminService.suspend(owner.id, 'Policy violation');
  await assert.rejects(authService.login('owner@example.com', 'owner-pass-1'), /suspended/);
  await assert.rejects(publicChatService.metadata('widget', widgetOn.public_id), /unavailable/);
  await assert.rejects(adminService.suspend('demo_admin', 'no'), /protected/);
  await adminService.reactivate(owner.id, 'Appeal accepted');
  await authService.logout();
  await authService.login('owner@example.com', 'owner-pass-1');
  assert.equal((await authService.me()).totp_enabled, false, 'admin MFA reset removed the authenticator');

  // --- password change needs the current password; social and linked accounts; email change ---
  await assert.rejects(authService.changePassword('wrong-current', 'brand-new-pass-3', 'brand-new-pass-3'), /Current password is incorrect/);
  await authService.changePassword('owner-pass-1', 'brand-new-pass-3', 'brand-new-pass-3');
  const pendingEmail = await authService.updateProfile({ full_name: 'Owner', email: 'owner2@example.com' });
  assert.equal(pendingEmail.email, 'owner@example.com'); assert.equal(pendingEmail.pending_email, 'owner2@example.com');
  await authService.confirmEmailChange(pendingEmail.verification_token);
  assert.equal((await authService.me()).email, 'owner2@example.com');
  await authService.logout();
  await assert.rejects(authService.loginWithSocial('GOOGLE', 'owner2@example.com', 'Owner'), /Confirm your password/);
  await assert.rejects(authService.loginWithSocial('GOOGLE', 'admin@gmail.com', 'Admin'), /Administrators/);
  assert.deepEqual((await authService.loginWithSocial('GOOGLE', 'owner2@example.com', 'Owner', 'brand-new-pass-3')).linked_accounts, ['GOOGLE']);
  assert.equal((await authService.loginWithSocial('GITHUB', 'fresh@example.com', 'Fresh')).signup_method, 'GITHUB');
  await authService.logout();

  // --- account deletion with 7-day restore ---
  await authService.login('owner2@example.com', 'brand-new-pass-3');
  await assert.rejects(authService.requestDeletion('wrong@example.com'), /Retype your email/);
  const deletion = await authService.requestDeletion('OWNER2@example.com');
  assert.ok(Date.parse(deletion.restorable_until) > Date.now() + 6 * 86400000);
  await assert.rejects(authService.me(), /Please sign in/);
  const back = await authService.login('owner2@example.com', 'brand-new-pass-3');
  assert.equal(back.status, 'PENDING_DELETION');
  await assert.rejects(chatbotService.list(), /scheduled for deletion/);
  await assert.rejects(publicChatService.metadata('share', link.public_id), /unavailable/);
  await authService.restoreAccount();
  assert.ok((await chatbotService.list()).length >= 1);
  await authService.requestDeletion('owner2@example.com');
  const stale = userRepository.all().find(u => u.email === 'owner2@example.com');
  userRepository.put({ ...stale, deletion_requested_at: new Date(Date.now() - 8 * 86400000).toISOString() });
  await purgeExpiredAccounts();
  assert.equal(userRepository.all().some(u => u.email === 'owner2@example.com'), false, 'accounts past the restore window are erased');
  await assert.rejects(publicChatService.metadata('share', link.public_id), /no longer available/, 'deleted chatbots report that they are gone');

  // --- platform overview, monitoring, LLM status ---
  await asAdmin();
  const platform = await insightsService.platform();
  assert.ok(platform.total_users >= 3); assert.equal(typeof platform.messages_this_month, 'number'); assert.ok(platform.token_usage >= 0);
  await platformService.setLlmStatus('OLLAMA', 'DOWN');
  const monitoring = await insightsService.monitoring();
  assert.match(monitoring.alerts[0], /OLLAMA is down/);
  assert.ok((await notificationService.list('PUSH')).some(n => n.type === 'ADMIN_LLM_UNAVAILABLE'));
  await platformService.setLlmStatus('OLLAMA', 'OPERATIONAL');
  await platformService.setSystemFallbackModel('Qwen');
  assert.equal((await insightsService.monitoring()).system_fallback_model, 'Qwen');
  await assert.rejects(platformService.setSystemFallbackModel('Ghost'), /enabled model/);
  assert.equal((await catalogService.embeddingModels()).length, 2);
  assert.equal(window.localStorage.getItem(KEYS.session) !== null, true);
  console.log('PASS v5: migration, password policy, lock-out, verification, lifecycle, publish checklist, guest messages, quotas, limits, duplicates, crawl, channels, feedback, reports, analytics, appeals, moderation, audit, suspension, sessions, MFA, passkeys, social linking, email change, account deletion/restore, monitoring.');
})().catch(error => { console.error(error); process.exitCode = 1; });
