"""durable vector cleanup and citation snapshots

Revision ID: 605e885948c8
Revises: 43dab0e7e4d1
"""
from alembic import op
import sqlalchemy as sa

revision = '605e885948c8'
down_revision = '43dab0e7e4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_cleanup_jobs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('chatbot_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vector_cleanup_jobs'))
    )
    op.create_index(op.f('ix_vector_cleanup_jobs_next_attempt_at'), 'vector_cleanup_jobs', ['next_attempt_at'], unique=False)
    op.add_column('message_sources', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.add_column('message_sources', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.add_column('message_sources', sa.Column('excerpt', sa.Text(), nullable=True))
    op.create_index(op.f('ix_message_sources_document_id'), 'message_sources', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sources_document_id'), table_name='message_sources')
    op.drop_column('message_sources', 'excerpt')
    op.drop_column('message_sources', 'chunk_index')
    op.drop_column('message_sources', 'document_id')
    op.drop_index(op.f('ix_vector_cleanup_jobs_next_attempt_at'), table_name='vector_cleanup_jobs')
    op.drop_table('vector_cleanup_jobs')
    # ### end Alembic commands ###
